---
repos:
  - repo: "https://github.com/adrienverge/yamllint.git"
    rev: "v1.29.0"
    hooks:
      - id: yamllint
  - repo: "https://github.com/dnephin/pre-commit-golang.git"
    rev: "v0.5.1"
    hooks:
      - id: go-fmt
  - repo: "https://github.com/psf/black.git"
    rev: "23.1.0"
    hooks:
      - id: black
  - repo: "https://github.com/hadolint/hadolint.git"
    rev: "v2.12.0"
    hooks:
      - id: hadolint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
